# Generated by Django 4.2.7 on 2023-11-23 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_coments_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='coment_date',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Час'),
        ),
    ]
