# Generated by Django 4.2.7 on 2023-11-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_teg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teg',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='tegs',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.teg', verbose_name='Теги'),
        ),
    ]
