# Generated by Django 4.2.7 on 2023-12-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_teg_post_post_tegs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Емейл')),
            ],
            options={
                'verbose_name': 'Емейл',
                'verbose_name_plural': 'Емейли',
            },
        ),
    ]
